apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: AgDRUVMHkw5H7YAO46MUM5Z80oyQg/EzNEor4A7YPNg060ROp2lcYy9I4+fmd9zH40ukCwq4wk7kSs+jihlv9
LydWppkXd2JtITFVSDi4CZ48sTd2dAplzzESdIbeyhU9mA2Vc2K3t1fqzdCTcsA5ktP9O7jk3mRJL+vkm2e9QWKGfrqVXTDjIw/lQ
IF9VYWwITJE3Ua+YPjy+iCwYO3V3TH5ZpT1fZQaVvCkeewjtUe7/6c5K22oNXVOFqpVO3tURUA1p0VO+77TsUlMut00cER+Qkxs8l
aMliWaRpIP1Omg+ZyniJV9AVd1+gWFNp7MrxjCT3U3GI+kV7KkzAqs43pbq0a+jKwBwMfe+6P2rqBn2ZubbPisxgyAPyyU4ru4Add
3StELP+rC7MnLPXH5Va5RgNCnwlRIujnjpyc30rniHfrnaIXF4W33Ltwjt00/6IKdon/rZJIgwCz88Fo8UxRXfIASAa/+lKs13F62
1ejJ8Hmch9vv3amOqcAttKW3fqUzX1ZEtfYIWuKxTgwTQlAI8Eh/23AGouNaD7MJvydcySDC9sn8SqHtItnt6w7KoZiodNpe8Dw3k
L24m1Uy3+QrXKk9ntm/WmHV1e/qeTRw96Y0fntexgmbCqUmbfv7kmhtjZcPLe4P0PFCGHFcOTHpxsaiV3CGTo0ATgwhettOOP0EYx
Im6gFCNZZ4wtstnTUknPvZC6KcZslx62iSYGiDd/iTezFVcPvGfHqiY7E3Xw=
    password: AgA4aDRzp9SYVx7KFIimR0d2suZlX78NcDy0CdL7a1ZRKFPx6o66S+0bYyEOXoucgTyQIOAO4PJiSGR0dzqTUIr
aWLiL1kk0YYJ7Og4BC37ODSOZN9OmMFtCEJDjymbpKMQkSQbv5G7TTj3MjUuNfrwOGnQJY9yWNIZMRQvX4DuSprbdJO5/n+rtDKqu
0swG8TcR4aw5lBfJxMI3WV+sxEW7y7wsBFqPFpwPZXWnxTljzqRhe1DOyKrf/ZHOT1embX0FjHZ/Hc/srQphBp2pD+UiLL+PfCtyR
UYJ4MZ8vzwF9manxZ4Mg2CFdk33avStbS6nOTf8cx2eMBrQRk9eQaSy5uNBmZRn0YoTvGTd5SpmimJd7s2sHNkkEMsC2TuLl+jgB7
RXfLNZH9dbMFQLsZsRhQyZtkTM5Cr5A2W8WndQgRimom+OKefXhaA+FOOLsU56jZ9cpUdH5e2kFPAMbGJ4bheu1k0qPSUyLj6Kwkf
EI7YzPM4gRcW7YQbfZPsUOBfK/qbj/O5bc0AKIx1LR4mzzcDZuOlwaIdGBJRwH6nZaEUSveF12R5SLl+kGUX+AStZ4Zwo2QehVfLC
ufLu6mIhHYe7CEHlHXNNuo0fkYNh40Ilx7uAJmMBR2p0IRb3h9N2ByMYjWROhHla/i/0D0IgIZxgY5P7deszZtjvDHPwXzb+3zfMV
D3HkanWm37/hHHSyAp/yBQomHv3bg69Jz0=
    username: AgBo8YrZouH/hi2GpMEvXJ+yrWBKgWxMET6MnVspBXQ7z8k6Ys08lbngrsfB3i03S9X3Pafb7TG85xVHNZ8CBYe
13D2GkC3VjVuwem9sDHi0qJy+5WVwv44fgjz1Uy8mfTLbvu06fzl0rk578ydCzQkX8+YoZr+KsY87r+f3h3m+BIheHFtUyHQqIOdh
qdITXDx4mrLER1RLnyU7Gy9JcKZo0IBj7jM0BGcQqucN2c3J3l10gTjN/nCkpL50I+Cp8/unFWdsgTU850T67xwv1tV1tpBFHdf9X
Cu3t5q8izfqhHzl/fFETTZLTkgoU5mjd9g6Lafy6/dl5iAe4+BBa+2aYnkzohqlZyMPss22ABEdrVJyGr2yujkwYWIQ2Eu6p0tmVU
8TYd2+Rl5wqgDFbrkcz0HUvRnUSiDUer/LGoyBErdFurHOse9duiRRjWL10OYywBtNscHPRun+HI0eyfkSoXBaV6GJM09XWkxUJ/x
mPVqymb7xelcAeSt7xAttScV1eLSXWzU2Yifad+NBhgZvvWO7T6KiU+4vf4VaysJdeNgeCxtXIIv7U89chjBYKta9zQjOvWU9ZDKl
J8+qa2j6faOyJM547Tap25YF9A3fIZ5o0kBlhVPWXHOnRii4pnQ3FruUrQFjJStljOxibuTi3BUN8yuyui/o6A5xDJ9nKsh6sTOO6
vQeIpdEFW67jIpd53aqWsIQZiHqYg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque
